// product.js
const PRODUCTS = [
    { num: 1, id: "socling_bike", name: "BICICLETA ELECTRICA PLEGABLE SOCLING", price: 700, image: "#", fullDescription: `ESPECIFICACIONES:<br>• 500 W - 48 V - 10 AH<br>• velocidad maxima: 32 km/h<br>• autonomia de 40-50km<br>• Luces LED, Frenos de Disco, Amortiguadores, Llantas de Balon 14'<br>• Doble Asiento y Plegable<br>• Carga 330Lb<br>• BATERIA DE LITIO<br>• INCLUYE: cesta, candado, portacelular, cargador inteligente, llaves, manual y herramientas<br>TRANSPORTE INCLUIDO<br>GARANTIA 7 DIAS<br>COLOR: NEGRO<br>FORMA DE PAGO: USD EFECTIVO , ZELLE<br>PRECIO: 700 USD` },
    { num: 2, id: "lanx_station", name: "Estacion de energia portatil LANX 600W", price: 450, image: "#", fullDescription: `• Tipo de bateria LiFePO4<br>• Inversor Onda sinusoidal modificada<br>• Fuente: Adaptador CA, Panel solar, Coche<br>• Controlador MPPT<br>• Tipo C - Carga Rapida QC3.0-PD<br>• Potencia nominal: 600W<br>• Voltaje sistema: 12.8V<br>• Incluye panel solar plegable y 3 bombillos LED<br>Transporte incluido<br>PRECIO: 450 USD` },
    { num: 3, id: "must_hbp33", name: "MUST HBP33-3024 TLV | Todo en uno solar 3kW", price: 2350, image: "#", fullDescription: `Modelo: MUST HBP33-3024 TLV<br>POTENCIA: Inversor 3,000 W, Onda sinusoidal pura<br>BATERIA: 7,168 Wh LiFePO₄, 24V<br>MPPT integrado, compatible paneles solares<br>Salida 110-120V AC<br>Transporte incluido<br>PRECIO: 2350 USD` },
    { num: 4, id: "bateria_respaldo_6000w", name: "Bateria de Respaldo 6000W - 14338Wh", price: 3250, image: "#", fullDescription: `SISTEMA TODO EN UNO (Inversor + Bateria + Controlador Solar)<br>• Voltaje: 120V - 240V<br>• Potencia inversor: 6000W<br>• Potencia bateria: 14338Wh<br>• Bateria Litio segura y duradera<br>• Facil movimiento con ruedas<br>• Respaldo confiable para apagones<br>• Ideal para hogar o negocio<br>• Funciona con red electrica y paneles solares<br>• Carga rapida<br>Transporte incluido<br>PRECIO: 3250 USD` },
    { num: 5, id: "sistema_hibrido_6000w", name: "Sistema Hibrido 6000W - 14338Wh", price: 3350, image: "#", fullDescription: `TODO EN UNO (Inversor + Bateria LiFePO4 + MPPT)<br>• Voltaje 120V-240V<br>• Potencia inversor 6000W<br>• Capacidad 14338Wh<br>• Ruedas para movilidad<br>• Respaldo automatico ante apagones<br>• Uso domestico / comercial<br>• Carga solar + red electrica<br>• Ampliable con mas baterias o paneles<br>Transporte incluido<br>PRECIO: 3350 USD` },
    { num: 6, id: "triciclo_electrico", name: "Triciclo Electrico de Paseo (Nuevo)", price: 2300, image: "#", fullDescription: `Triciclo electrico nuevo a estrenar<br>• Bateria Litio 72V 35Ah<br>• Velocidad maxima: 40 km/h<br>• Autonomia 80-90 km por carga<br>• Color: Negro<br>• 10 unidades disponibles a partir del miercoles<br>Transporte incluido<br>PRECIO: 2300 USD` },
    { num: 7, id: "ecoflow_delta3_plus", name: "EcoFlow Delta 3 Plus 1024Wh", price: 950, image: "#", fullDescription: `EcoFlow Delta 3 Plus<br>• Capacidad: 1024 Wh (expandible hasta 5 kWh)<br>• Salida AC: 1800W (3600W pico)<br>• Bateria LFP (4000 ciclos)<br>• Carga rapida 0-100% en 56 min<br>• Entrada solar 500W MPPT<br>• Wi-Fi / App EcoFlow<br>• Ultrasilenciosa <30 dB<br>Transporte incluido<br>Garantia 15 dias<br>PRECIO: 950 USD` },
    { num: 8, id: "ecoflow_delta3_max", name: "EcoFlow Delta 3 Max 2048Wh", price: 1380, image: "#", fullDescription: `EcoFlow Delta 3 Max<br>• Capacidad: 2048 Wh<br>• Potencia continua 2400W (3400W X-Boost)<br>• Carga ultrarrapida: 0-80% en 1.13h<br>• Transferencia automatica 10ms<br>• Bateria LiFePO4 (10 anos vida util)<br>• App con control inteligente<br>Transporte incluido<br>Garantia 15 dias<br>PRECIO: 1380 USD` },
    { num: 9, id: "ecoflow_delta3", name: "EcoFlow Delta 3 1024Wh", price: 880, image: "#", fullDescription: `ECOFLOW DELTA 3<br>• Capacidad: 1024Wh LiFePO4<br>• Potencia salida: 1800W (pico 3600W)<br>• Tiempo carga 0-100%: 56 min<br>• Soporta panel solar 500W<br>Transporte incluido<br>Factura y garantia<br>PRECIO: 880 USD` },
    { num: 10, id: "bluetti_ac180", name: "BLUETTI AC180 1152Wh 1800W", price: 800, image: "#", fullDescription: `BLUETTI AC180<br>• Capacidad: 1152Wh LiFePO4<br>• 2 salidas CA de 1800W (pico 2700W)<br>• 0-80% en 45 minutos<br>• Ideal para camping, fuera de red<br>Factura<br>Transporte incluido<br>PRECIO: 800 USD` },
    { num: 11, id: "bluetti_ac180p", name: "BLUETTI AC180P 1440Wh 1800W", price: 850, image: "#", fullDescription: `BLUETTI AC180P<br>• Capacidad: 1440Wh / 1800W<br>• Modo Power Lifting: 2700W pico<br>• 9 puertos de salida<br>• 4 metodos de carga (CA/solar/vehiculo/generador)<br>Factura<br>Transporte incluido<br>PRECIO: 850 USD` },
    { num: 12, id: "ecoflow_delta_pro", name: "EcoFlow Delta Pro 3600Wh", price: 2300, image: "#", fullDescription: `EcoFlow Delta Pro (Nuevo en caja)<br>• Capacidad: 3600Wh<br>• Potencia nominal 3600W (pico 7200W)<br>• Expandible hasta 25kWh<br>• Carga solar rapida<br>• Transferencia automatica<br>Transporte incluido<br>Garantia<br>PRECIO: 2300 USD` },
    { num: 13, id: "ecoflow_delta2_max", name: "EcoFlow Delta 2 Max 4800W", price: 1360, image: "#", fullDescription: `EcoFlow Delta 2 Max<br>• Capacidad: 2048 Wh<br>• Potencia nominal: 2400W<br>• Potencia pico: 4800W<br>• Garantia y factura ✅<br>• Transporte incluido en La Habana<br>PRECIO: 1360 USD` },
    { num: 14, id: "ecoflow_delta3_pro", name: "EcoFlow Delta 3 Pro 110/220V", price: 3150, image: "#", fullDescription: `EcoFlow Delta 3 Pro<br>• Potencia nominal: 4000W<br>• Potencia pico: 8000W<br>• Capacidad: 4096Wh<br>• Voltajes: 110V y 220V<br>• Garantia y papeles<br>• Mensajeria incluida<br>PRECIO: 3150 USD` },
    { num: 15, id: "ecoflow_delta3_classic", name: "ECOFLOW DELTA 3 CLASSIC", price: 800, image: "#", fullDescription: `ECOFLOW DELTA 3 CLASSIC<br>• Capacidad: 1024Wh<br>• Potencia salida: 1800W (pico 3600W)<br>• Carga completa AC en 1.5 horas<br>• Factura y garantia ✅<br>• Transporte incluido<br>PRECIO: 800 USD` },
    { num: 16, id: "ecoflow_delta2", name: "ECO FLOW DELTA 2", price: 780, image: "#", fullDescription: `ECO FLOW DELTA 2<br>• Capacidad: 1024Wh<br>• Salida: 1800W (pico 2700W)<br>• Carga al 80% en 50 min<br>• Admite carga solar 500W (panel no incluido)<br>• Multiples salidas: AC, USB-C, USB-A, DC<br>• Wi-Fi, Bluetooth, bateria LiFePO₄ 3000 ciclos<br>• Nueva en caja, garantia 15 dias, factura<br>• Transporte incluido ✅<br>PRECIO: 780 USD` },
    { num: 17, id: "freidora_milexus", name: "Freidora de Aire Milexus 4.2L", price: 90, image: "#", fullDescription: `Freidora de Aire Milexus ML-AF-901<br>• Capacidad: 4.2 L (bandeja 3.7 L / cajon 4.21 L)<br>• 120V - 60 Hz - 1400 W<br>• Cuerpo plastico mate, cajon antiadherente desmontable<br>• Proteccion sobrecalentamiento<br>• Temperatura ajustable 60-200°C<br>• Panel tactil con preestablecidos, precalentamiento, mantener caliente, recordatorio de agitacion<br>• Apagado automatico, almacenamiento cable, patas antideslizantes<br>• Cocina con poco o sin aceite<br>Transporte incluido<br>PRECIO: 90 USD` },
    { num: 18, id: "refrigerador_samsung", name: "Refrigerador Samsung Side by Side 20cuft", price: 1250, image: "#", fullDescription: `Refrigerador Samsung Side by Side<br>• Capacidad: 20 pies cubicos<br>• Formato Side by Side (SBS)<br>• Dispensador de agua en puerta<br>• Sistema All Around Cooling<br>• Estantes de vidrio templado<br>• Cajones para frutas y vegetales<br>• Iluminacion LED, acabado plateado moderno<br>• Dimensiones aprox.: 91 × 178 × 71 cm<br>Transporte incluido<br>PRECIO: 1250 USD` },
    { num: 19, id: "moto_topmaq_tank", name: "MOTO ELECTRICA TOPMAQ TANK 3000W", price: 3300, image: "#", fullDescription: `MOTO ELECTRICA TOPMAQ TANK<br>• Motor y bateria TOPMAQ<br>• Potencia: 3000W<br>• Voltaje: 72V<br>• Bateria: 45AH<br>• Autonomia: 120 km<br>• Caja reguladora VOTOL EM-50<br>• Colores: ROJO<br>• Formas de pago: USD, EUR, MN, ZELLE<br>TRANSPORTE INCLUIDO<br>PRECIO: 3300 USD` }
];